security:
    providers:
        user_provider:
            mongodb:
                class: App\Document\User
                property: username
    encoders:
        App\Document\User:
            algorithm: bcrypt
            cost: 12
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            remember_me:
                secret: "%kernel.secret%"
                lifetime: 604800 # 1 week in seconds
                path: /
                always_remember_me: true
            provider: user_provider
            logout:
                path: app_logout
    access_control:
